apiVersion: v1
kind: Service
metadata:
  name: top-service-api-service
spec:
  ports:
    - name: webserver
      port: {{ .Values.module.serviceApi.port }}
      protocol: TCP
      targetPort: webserver
  selector:
    app: top-service-api
