apiVersion: v1
kind: Service
metadata:
  name: iot-api-service
spec:
  ports:
    - name: tcp-8090
      port: {{ .Values.module.iotApi.port }}
      protocol: TCP
      targetPort: webserver
  selector:
    app: iot-api
