apiVersion: v1
metadata:
  name: nginx-ingress-nginx-tcp
  namespace: ingress-nginx
  annotations:
    meta.helm.sh/release-name: nginx
    meta.helm.sh/release-namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.47.0
    helm.sh/chart: ingress-nginx-3.34.0
kind: ConfigMap
data:
  "1883": default/emqx-service:1883
  "8883": default/emqx-service:8883
