apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-manager-deploy
  labels:
    app: data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-manager
      tier: pod
  template:
    metadata:
      name: top-data-manager-pod
      labels:
        app: data-manager
        tier: pod
    spec:
      containers:
        - name:  data-manager
          image: {{ printf "%s:%s/%s:%s" .Values.global.registryHost .Values.global.registryPort .Values.module.dataManager.name .Values.module.dataManager.tag }}
          ports:
            - name: webserver
              containerPort: {{ .Values.module.dataManager.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.configMap }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
