apiVersion: v1
kind: Service
metadata:
  name: data-manager-service
spec:
  ports:
    - name: webserver
      port: {{ .Values.module.dataManager.port }}
      protocol: TCP
      targetPort: webserver
  selector:
    app: data-manager
