apiVersion: v1
kind: Service
metadata:
  name: cloudlet-service
spec:
  ports:
    - name: cloudlet
      port: 8094
      protocol: TCP
      targetPort: {{ .Values.module.cloudlet.port }}
  selector:
    app: cloudlet
