apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-api-deploy
  labels:
    app: common-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-api
      tier: pod
  template:
    metadata:
      name: top-pod
      labels:
        app: common-api
        tier: pod
    spec:
      containers:
        - name: server
          image: {{ printf "%s:%s/%s:%s" .Values.global.registryHost .Values.global.registryPort .Values.module.commonApi.name .Values.module.commonApi.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: webserver
              containerPort: {{ .Values.module.commonApi.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.configMap }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.redisSecretName }}
                  key: redis-password
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
