apiVersion: v1
kind: Service
metadata:
  name: common-api-service
spec:
  ports:
    - name: webserver
      port: 8091
      protocol: TCP
      targetPort: webserver
  selector:
    app: common-api
