apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-manager-deploy
  labels:
    app: push-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-manager
      tier: pod
  template:
    metadata:
      name: top-push-manager-pod
      labels:
        app: push-manager
        tier: pod
    spec:
      containers:
        - name: push-manager
          image: {{ printf "%s:%s/%s:%s" .Values.global.registryHost .Values.global.registryPort .Values.module.pushManager.name .Values.module.pushManager.tag }}
          ports:
            - name: webserver
              containerPort: {{ .Values.module.pushManager.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.configMap }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
