apiVersion: v1
kind: Service
metadata:
  name: push-manager-service
spec:
  ports:
    - name: webserver
      port: {{ .Values.module.pushManager.port }}
      protocol: TCP
      targetPort: webserver
  selector:
    app: push-manager
