# Default values for top.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  registryHost: "10.177.176.100"
  registryPort: "30050"
  imagePullSecrets: "regcred"
  imagePullPolicy: "IfNotPresent"
  configMap: "in-cluster-config"

module:
  iotApi:
    name: "top/iot-api"
    tag: "v1.0"
    port: "8090"
  commonApi:
    name: "top/common-api"
    tag: "v1.0"
    port: "8091"
  dataManager:
    name: "top/data-manager"
    tag: "v1.0"
    port: "8092"
  serviceApi:
    name: "top/service-api"
    tag: "v1.0"
    port: "8093"
  cloudlet:
    name: "top/cloudlet"
    tag: "v1.0"
    port: "8094"
  pushManager:
    name: "top/push-manager"
    tag: "v1.0"
    port: "8095"
  simulator:
    name: "top/simulator"
    tag: "latest"
    port: "8080"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
