# Default values for top.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  registryHost: "10.177.176.100"
  registryPort: "30050"
  imagePullSecrets: "regcred"
  imagePullPolicy: "IfNotPresent"
  tag: ""

module:
  iotApi: "top/iot-api"
  commonApi: "top/common-api"
  dataManager: "top/data-manager"
  serviceApi: "top/service-api"
  cloudlet: "top/cloudlet"
  pushManager: "top/push-manager"
  simulator: "top/simulator"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
