apiVersion: v1
kind: Service
metadata:
  name: simulator-service
spec:
  ports:
    - name: simulator
      port: {{ .Values.module.simulator.port }}
      protocol: TCP
      targetPort: simulator
  selector:
    app: simulator